# Generated by Django 5.2.7 on 2025-10-16 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iin",
                    models.CharField(max_length=20, unique=True, verbose_name="ИИН"),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        default="Aa123456", max_length=128, verbose_name="Пароль"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "🟡 В очереди"),
                            ("registered", "🟢 Зарегистрирован"),
                            ("tested", "✅ Тест сдан"),
                            ("completed", "📄 Сертификат скачан"),
                            ("failed", "❌ Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "score",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Результат теста (%)",
                    ),
                ),
                (
                    "certificate_file",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Путь к сертификату",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Комментарий / ошибка"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="AutomationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage", models.CharField(max_length=50, verbose_name="Этап")),
                ("success", models.BooleanField(default=False, verbose_name="Успешно")),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Сообщение"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="main.useraccount",
                    ),
                ),
            ],
        ),
    ]
