# Generated by Django 5.2.7 on 2025-10-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="has_error",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="is_downloaded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="is_registered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="is_tested",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
